#!/usr/bin/env python

# -----------------------------------------------------------------------------
# Copyright (c) 2014--, The Qiita Development Team.
#
# Distributed under the terms of the BSD 3-clause License.
#
# The full license is in the file LICENSE, distributed with this software.
# -----------------------------------------------------------------------------

import click

from qp_deblur import plugin


@click.command()
@click.option('--env-script', prompt='Environment script',
              default='source activate qp-deblur')
@click.option('--server-cert', prompt='Server certificate', default='None')
@click.option('--plugin-coupling', prompt="Type of coupling of plugin to central for file exchange. Valid values are 'filesystem' and 'https'", default='filesystem')
def config(env_script, server_cert, plugin_coupling):
    """Generates the Qiita configuration files"""
    if server_cert == 'None':
        server_cert = None
    plugin.generate_config(env_script, 'start_deblur',
                           server_cert=server_cert, plugincoupling=plugin_coupling)

if __name__ == '__main__':
    config()
